version: '3.8'

services:
  issuance-service:
    build:
      context: ./backend/issuance-service
      dockerfile: Dockerfile
    container_name: issuance-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - WORKER_ID=issuance-worker-1
    volumes:
      - issuance-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  verification-service:
    build:
      context: ./backend/verification-service
      dockerfile: Dockerfile
    container_name: verification-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - WORKER_ID=verification-worker-1
      - ISSUANCE_SERVICE_URL=http://issuance-service:3001
    volumes:
      - verification-data:/app/data
    depends_on:
      - issuance-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - VITE_ISSUANCE_SERVICE_URL=http://localhost:3001
      - VITE_VERIFICATION_SERVICE_URL=http://localhost:3002
    depends_on:
      - issuance-service
      - verification-service
    restart: unless-stopped

volumes:
  issuance-data:
  verification-data:



